name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  first-job:
    runs-on: windows-latest
    steps:
      -run: node --version
      -run: npm -version
